<?php /** @var \Nord\Shipfunk\Block\Adminhtml\Order\View\Custom $block */ ?>
<?php if ($block->hasPickupInformation()) { ?>
<div id="shippingPickupInformation">
    <div class="admin__page-section-item-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Pickup Point') ?></span>
    </div>
    <div class="admin__page-section-item">
        <strong class="admin__page-section-item-content"><?= $block->getPickupInformation() ?></strong>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
        $('#shippingPickupInformation').appendTo($('.order-shipping-method'));
    });
</script>
<?php } ?>
