<?php /** @var \Nord\Shipfunk\Block\Adminhtml\Order\View\Custom $block */ ?>
<?php if ($block->hasPickupInformation()) { ?>
<div id="shippingPickupInformation">
    <div class="admin__page-section-item">
        <?= $block->escapeHtml($block->getPickupInformation(), ['br']) ?>
    </div>
</div>
<script>
    require(['jquery'], function ($) {
      $(document).ready(function() {
        $('#shippingPickupInformation').appendTo($('.order-shipping-method'));
      });
    });
</script>
<?php } ?>
